### ISSUE TITLE
I get this error during compilation of the example. 

### ISSUE THREAD

**Issue by bwghughes** [lucasnewman/f5-tts-swift#2]
I am on 15.1 Beta (24B5055e) 

```
note: class 'MLXArray' does not conform to the 'Sendable' protocol
  6 | import Numerics
  7 |
  8 | public final class MLXArray {
    |                    `- note: class 'MLXArray' does not conform to the 'Sendable' protocol
  9 |
 10 |     /// Internal pointer to the mlx-c wrapper on `mlx::core::array`, used with `Cmlx` interop.
```

I have the following Package.swift:

```
import PackageDescription

let package = Package(
    name: "tts",
    platforms: [
        .macOS(.v14)
    ],
    dependencies: [
        .package(url: "https://github.com/lucasnewman/f5-tts-swift.git", branch: "main")
    ],
    targets: [
        .executableTarget(
            name: "tts",
            dependencies: [
                .product(name: "F5TTS", package: "f5-tts-swift")
            ])
    ]
)
```

**Comment by lucasnewman** [comment]
I think the specific Sendable error there is coming from the usage, so it depends on how you're using in your code.

I'm not sure how MLXArray interacts with the Swift Concurrency model in Swift 6+, but based on the error it looks like there might be some underlying framework support needed to either tag with @preconcurrency or to make MLXArray actually Sendable. The lazy evaluation semantics might make this [tricky](https://swiftpackageindex.com/ml-explore/mlx-swift/0.12.1/documentation/mlx/mlxarray) — it's probably worth asking the folks who maintain mlx-swift.

You could consider switching back to the Swift 5.9 language model in the meantime if your project allows it.
